### PR TITLE
Acquire the message outside lock in synchronous execution mode

### LINKED ISSUE #49: Vulnerability to deadlocks with synchronous execution method
I just came across https://github.com/JohnEstropia/CoreStore/issues/304 issue, where Willow is partly to blame, specifically [these lines](https://github.com/Nike-Inc/Willow/blob/a8750591c8b5df1fabe7fe02baa28734305d512f/Source/Logger.swift#L168-L169):

```swift
lock.lock() ; defer { lock.unlock() }
logMessage(message(), with: logLevel)
```

The message shouldn't be acquired within the lock. While the recursive lock handles deadlocking, there're a many cases where people somehow manage to get them. The aforementioned case is another example.

### PR DESCRIPTION
**Pull request by iby**
Fixes #49 – see for details.

### CODE REVIEW

**Review by cnoon — APPROVED** [review]
Looks good @ianbytchek...thank you for putting this together! 🍻

**Comment by cnoon** [comment]
@ianbytchek could you sign the CLA so we can get this pushed through and released?

**Comment by iby** [comment]
@cnoon done!

**Comment by cnoon** [comment]
Awesome, thanks @ianbytchek! 🍻

**Review by jereme — APPROVED** [review]

**Pull request merged**
